import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../lib/Provider";
import { Rubik } from "next/font/google";
export const metadata = {
  title: "savisoft",
  description: "Generated by Istiak Hasan",
};
const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-pO+6+mPBLv5Q+5eEONp2+QF4A2C/cIq8+G2YpKk3M0lWxUoQ0F8ZZBkCkF7Ck8rM5k2c2E3Gv7bq5qD70Gm7Hw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={rubik.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
